"""Shared test helpers and constants."""

# Valid (fake) service account key JSON for use in tests that need to
# construct a Credentials object via load_credentials.
VALID_KEY_JSON = (
    '{"type": "service_account", "project_id": "test",'
    ' "client_email": "test@test.iam.gserviceaccount.com",'
    ' "token_uri": "https://oauth2.googleapis.com/token",'
    ' "private_key": "-----BEGIN PRIVATE KEY-----\\n'
    'MIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQDRPTiNfUy3C1hp\\n'
    'U29KCrCIKpXNi9QlC+yGoqe4YYshM2KU98iZd1VzUmSzl3z9l3fJDwpL+I0Mzy3j\\n'
    'sqkZuK2o+l8UTmnRUUCtYMWEkUBatSqCefMLETRbZKj5WAxLgfmfHhRIyj3+PQGL\\n'
    'guBd+1GzCGY+53aqgqDGj9e68YULMm1vhN3kMFO/AQCEaNzKMc9XUFRL70xFLOIT\\n'
    'deQnL1mxuDobMv1UDeX8/CUQTlv3Z4gRI0D2AatFs6636D4ARpaXgC+TD0Wgf+5n\\n'
    't+SDIl41Wzfvsme7tuppCNenqZlSry1yikYrAuJv+2+DZivG/E+wGA7d7SCZo/ck\\n'
    'x3+O4r0xAgMBAAECgf8Bowpc08iMHbDdzpfl2kzF2jDTNqbpK6F+EFFtfb+Zlayh\\n'
    'Jg8Xgt291QqoHQPL6imxjzsrpreEdk9UM9DolWMDn2ariaZfJHvub/3Nqv73+XnO\\n'
    'cRDrPvwUTm8GwY5y5JkQBOi+JkCfpDIwShUfm/cELXLnqxMEqtA/hcNWHBobkHn6\\n'
    'QzE5FWilICeaH0WNOngLbYv1pZgamj7y9EeoIL/XP+n57hI8jKi5Oz2LOAJwgRbn\\n'
    'BHsc8SvhMaUz5uNWNbRBefbGNA76yLPd7ZzZRZa0Iw3vNCajeBaMJWqS49qvKjS1\\n'
    'cadX6zp/+T05JQtq65xdUdGVS/urdnzCtJdV8OECgYEA8K1PU1vnkYv76PFBcg62\\n'
    'pIITLZqF+wMNerER0VZNLAmh9jCrzMuRYhnySZ9HdVGefo/ic80wvo4XitFmA+UP\\n'
    'o4xUkAIFSNwVcyE0Ujnn69RaC/iBFvHlIiVF9gdW/1E+McGXNAtk8bW8JJZNi4th\\n'
    'rHR0wPcTuo2ukoY3tNKSrRECgYEA3o+E6HDTiCQ0k6i7NI5QlrHLstGiXVFGZrLB\\n'
    'E5FJ4RDDVIlrOzVTU3E2D8r/YuriK1GKEkRgJTJrcV6PogZf6/wUvxedG+mRXTfh\\n'
    'iJiY8HmoQcNwDGAqOBUlpebs/ve0hRIobkFqXcLNBgB1LO3CxEm+mTK+3UrLbOGe\\n'
    '7LpLjiECgYBuHr4m4+wmWihewtQw/a5vwtxHh2Y6HYFzW8VNRPF2bsnePRK+V34j\\n'
    'pr+HFAu8ECY2vlrcpUviRF1dNMY6jfoD2NdwNJx6Y8ikrtKjtL761mSFCaT2/KLc\\n'
    'ZrWGBoG1vFR6q5slQvli5sY471R3vsRoBbjN+b7bIqx3elXOtHJMIQKBgHb8yBP1\\n'
    'bkJVCP8AsMWSaKeIet0pkuLNNxRk8TDi9lqruaKSrY/EHL55wmuDHjLmXPDH8Ud+\\n'
    '4uBAKo07/xKi0dm6teTMXSS1JRBvddavruSyRjCSqm8TYr8FH1GpOn++MvcKFC+O\\n'
    'La3fHfndeMgCfaSvwITrSnvJJyUZIvxxRT/BAoGAPmRj3AiEv4tBZaiB/FrpPGEo\\n'
    'RPZ21slNoYt//dkTUixnqn8iXP9fxZVfg291R+D1cayx02/IHAANN1bORKieWODv\\n'
    'ln22ArhfMT13kbnqrRZpNTHb+iZKz6Z+wa/BKw2+NJqg7PQpWAAj6VSTlqzGruW9\\n'
    'FiCTRCUWN7nMpNoN4nw=\\n-----END PRIVATE KEY-----\\n"}'
)
